language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - "yarn build-for-gh"

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  verbose: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master